- src/app/(pages)/Hackathon/[id]/page.jsx
- src/app/(pages)/Hackathon/page.jsx
This is in response tot he issue #147
> added details page

- src/components/Global/Header.jsx
> Fix Navbar On the Application 

- src/app/(pages)/womentechmakers/page.jsx
fix: #177
This PR introduces a new "Women Techmakers" page to the application, dedicated to supporting and celebrating women in technology. The page provides information on the Women Techmakers program, resources, events, and opportunities for networking and growth. It aims to promote inclusivity and empower women within the tech community by providing visibility and access to valuable resources.
> Add Women Techmakers Page to Highlight Program and Resources for Women in Tech

- src/app/(pages)/participationterms/page.jsx
fix:  #179
This PR introduces a "Participation Terms" page, detailing the guidelines, rules, and expectations for user involvement within the platform. It clarifies acceptable behaviors, responsibilities, and rights, ensuring users understand the terms of participation. This addition enhances transparency and provides a reference for maintaining a positive and respectful community environment.
> Add Participation Terms Page to Outline User Guidelines and Expectations

- src/app/(pages)/helpCenter/page.jsx
- src/app/(pages)/participation-terms/page.jsx
fix: #206 
This PR adds a "Help" page to the application, offering users a centralized location for accessing support resources, FAQs, and guidance on common issues. The page is designed to assist users in navigating the application, resolving issues, and finding answers to frequently asked questions, improving overall user experience and accessibility to support.
> Add Help Page for User Assistance and Support Resources

- src/app/(pages)/gitContributors/page.jsx
fix: #176 
This PR adds a "Git Contributors" page to acknowledge and celebrate the contributions of developers and collaborators on the project. The page lists all contributors with their profiles, showcasing their roles and contributions, and linking to their GitHub profiles. This addition promotes community spirit, recognizing the collective effort that drives project success.
> Add Git Contributors Page to Recognize Project Collaborators

- src/app/(pages)/certifications/page.jsx
fix: #265 
This PR introduces a "Roadmap" page, providing users with insight into upcoming features, planned enhancements, and key milestones in the application's development. The page is designed to keep users informed about future updates, fostering transparency and engagement by showcasing the project's direction and long-term goals.
> Add Roadmap Page to Outline Future Development Plans and Milestones

- src/app/page.js
- src/components/Global/Hero.jsx
- src/components/ui/homepage.jsx
fix: #155 
fix: #245  
This PR completely redesigns the landing page to improve user experience, visual aesthetics, and engagement. Updates include a modernized layout, streamlined navigation, optimized content sections, and improved call-to-action elements. The new design aims to create a welcoming and informative first impression, making it easier for users to understand and explore the platform's offerings.
> Revamp Landing Page for Enhanced User Experience and Visual Appeal || add parallax effect

- src/app/(pages)/devfest/page.jsx
fix: #268 
This PR introduces a "Community DevFest" page, dedicated to providing information about upcoming DevFest events, workshops, and resources for developers. The page includes event details, schedules, and registration links, offering a centralized hub for community engagement and knowledge-sharing, encouraging participation and collaboration among developers.
> Add Community DevFest Page to Showcase Developer Festival Events and Resources

- src/components/Global/Navbar.jsx
bug: The navbar is not closing after clicking #305 
Closes: #305 
https://private-user-images.githubusercontent.com/93651229/381019405-5032882b-adcd-40ea-81d4-0ad7cb0e8b5f.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzQ4MDQsIm5iZiI6MTczMDI3NDUwNCwicGF0aCI6Ii85MzY1MTIyOS8zODEwMTk0MDUtNTAzMjg4MmItYWRjZC00MGVhLTgxZDQtMGFkN2NiMGU4YjVmLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA3NDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNjg5ZmIyM2I0ZjcxMzIyZmQ4MmM4NWQxNTllYzk5ODA3NWFmZjkxMDFlMDQ1OWRlNGJlYWM2ZjhmZDAxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0 …
>  bug: The navbar is not closing after clicking #305 

- src/app/(pages)/Practitioners/page.jsx
fix: #370 
The Developers & Practitioners page serves as a hub for technical professionals to access resources, best practices, and community insights. This page includes guides, tutorials, and case studies tailored for developers and practitioners, fostering a collaborative environment for sharing knowledge and enhancing skills in application development.
> ADD Developers & Practitioners Page to the application

- src/app/(pages)/partners/page.jsx
> ADD Partners Discover partners that can help you innovate faster with Google Cloud products and services

- .github/ISSUE_TEMPLATE/backend_issue.yml
*Enter the issue title here-* Backend Issue Report Template
---
*Describe the aim of the project-* To improve backend functionality and streamline issue reporting for better project tracking.
---
*Enter your name here-* Alolika Bhowmik
---
*Enter your GitHub ID here-* alo7lika
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hacktoberfest).**  
*Enter your participant role here-* Contributor GSSOC 2024
---
*Closes: #issue-number* Closes: #400
---
**Give a clear description of what you have added or modified.** …
> Backend Issue Report Template

- src/app/(pages)/whitepapers/page.jsx
> Add featured whitepapers page

- src/app/(pages)/garage/page.jsx
fix: #438 
A section inspired by Google’s original “garage startup,” encouraging innovative project ideas. It could showcase open-source projects and provide an “idea incubator” where developers can work on rough ideas, connect with others, or submit small scripts to share with the community.
> Add garage page for the application 

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/tech-stack-explorer/page.jsx
fix: #505
This PR introduces the **GDG Virtual Lounge**, a new section designed to provide a relaxed and informal virtual space for members of the community. The Virtual Lounge includes features that allow users to chat, share ideas, and network seamlessly.
- **Chat Rooms**: Real-time messaging for open discussions among members.
- **Discussion Boards**: Asynchronous threads for longer conversations, idea-sharing, and feedback.
- **Video Calls**: Integrated video call functionality for face-to-face interactions and meetings.
- **Scheduled Virtual Hangouts**: Events where members can join for informal networking sessions.
- Added components and services for chat rooms and discussion boards.
- Integrated video call support using WebRTC.
- Created scheduling system for virtual hangouts.
- …
> Tech stack explorer

- data.json
- src/app/api/Certifications/route.js
fix #493 
This PR introduces support for fetching certifications data from a JSON server, replacing the previous static import of certifications data. The changes include:
- **Implemented JSON Server for certifications :**
- Set up a local JSON server to provide dynamic certifications data.
- Updated the certifications page to fetch certifications data from the local server (`http://localhost:5000/certifications`).
- **certifications Page Updates:**
- Refactored the certifications component to retrieve and display certifications via the JSON server instead of a static `certifications` import.
- Implemented search and sorting functionality that filters and sorts certifications data fetched from the server.
- Set up a mock JSON server with certifications data in `data.json`.
- Updated …
> Added JSON Server Support in the Certifications Page | Issue #493

- src/app/(pages)/volunteer/page.jsx
> Add gdg history page to the application 

- src/app/(pages)/future-tech/page.jsx
> Add future page

- src/app/(pages)/confession/page.jsx
> Add tech confessions for the tech dev students 

- src/app/(pages)/detox-zone/page.jsx
> ADd detox zone page

- data.json
- src/app/(pages)/growth/page.jsx
fix #534 
1. Implemented Search Feature in Growth Page.
2. Implementated Filter Feature in Growth Page.
3. Added tags in the JSON data.
https://github.com/user-attachments/assets/7dc9a195-5181-4a00-b22b-b5ed4a2e8d28
---
> Added Search and Filter Features | Issue #534

- src/app/(pages)/ReverseEngineeringLab/page.jsx
> Add reverse engineering page to the application

- src/app/(pages)/whitepapers/page.jsx
fix #550 
I have added Search and Filter Functionality on the Growth Page.
1. Ensured Search Functionality.
2. Ensured Filter Functionality.
https://github.com/user-attachments/assets/ecddc9c8-ce36-4854-a1a7-93aa06bec782
> Added Search and Filter Features on Growth Page | PR 1 | Issue #550

- data.json
- src/app/(pages)/analyst-reports/page.jsx
fix #493 
This PR introduces support for fetching Analyst Reports data from a JSON server, replacing the previous static import of Analyst Reports data. The changes include:
- **Implemented JSON Server for Analyst Reports **
- Set up a local JSON server to provide dynamic Analyst Reports data.
- Updated the Analyst Reports page to fetch Analyst Reports data from the local server (`http://localhost:5000/reports`)
---
> Added JSON Server Support in the Analyst Reports Page | Issue #493

- data.json
- src/app/(pages)/devprod/page.jsx
fix #493 
This PR introduces support for fetching Dev Products data from a JSON server, replacing the previous static import of Dev Products data. The changes include:
- **Implemented JSON Server for Dev Products **
- Set up a local JSON server to provide dynamic Dev Products data.
- Updated the Dev Products page to fetch Dev Products data from the local server (`http://localhost:5000/devproducts`)
---
> Added JSON Server Support in the Dev Products Page | Issue #493

- src/app/(pages)/devprod/page.jsx
fix #550 
I have added Search and Filter Functionality on the DevProd Page.
1. Ensured Search Functionality.
2. Ensured Filter Functionality.
https://github.com/user-attachments/assets/fdb283ad-f62d-4da9-a204-05ace36a951b
> Added Search and Filter Features on DevProd Page | PR 3 | Issue #550 
