GDSC-RCCIIT/gdg-website

- src/app/(pages)/About.jsx
https://github.com/user-attachments/assets/46889153-3a7a-4859-9ada-4a0facfa7d19
This is in response to the issue #17
> About Page

- src/app/(pages)/SignIn.jsx
- src/app/page.js
This is in response to the issue #23
> SignIn Page

- src/app/(pages)/Events/EventItem.js
- src/app/(pages)/Events/Events.css
- src/app/(pages)/Events/Events.jsx
- src/app/page.js
I have completed and added a fully responsive events page for the GDSC RCCIIT On Campus.
https://github.com/user-attachments/assets/1cef2a97-a9b4-40e6-a48d-665d175cc520
Features :
1. A Complete and Dedicated Page for GDSC RCCIIT Events-related Information.
2. Fully Responsive and Well Structured.
3. Followed Modular Programming that facilitates easier addition of more events in future.
4. Followed Good UI and UX.
Issue #27 Completed
> Added A Fully Responsive Events Page For GDSC RCCIIT | Issue #27

- src/app/page.js
- src/components/Global/Header.jsx
@rishicds  Kindly checkout the PR and let me know
> Navigation Menu Header:- 2

- contributing.md
Added the Contributing.md file
closes :- #1 
@rishicds Please check this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level.
> Added the Contributing.md file

- code_of_conduct.md
Added Code of contduct.md 
closes :- #2 
@rishicds Please check this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level.
> Added Code of contduct.md 

- package-lock.json
- package.json
- src/app/page.js
- src/components/Global/Footer.jsx
This is in response to the issue #13 
@rishicds
> Footer made:- 3

- src/app/(pages)/Resource/Resource.jsx
I added Links to the roadmaps also
This is in response to the issue #37
> Resource Page

- package-lock.json
- package.json
> BUG Fix | Issue #67

- src/app/layout.js
- src/components/ui/progress-bar.jsx
I have added a multi-colored progress bar that also matches the theme of the GDSCs.
https://github.com/user-attachments/assets/deb15582-00c8-49e1-bbfc-47c17c3eed7d
Completed #58
> Added Progress Bar | Issue #58

- package.json
- src/app/layout.js
- src/components/ui/back2top.jsx
I have implemented and added the BackToTop button in the website, with smooth scrolling.
https://github.com/user-attachments/assets/ae1159ba-146b-4858-bbcc-4596b9ac1555
Completed #59
> Added BackToTop Button with Smooth Scrolling | Issue #59

- package-lock.json
- package.json
- src/app/(pages)/About/page.jsx
- src/app/layout.js
I have added the Validation in the Newsletter and also added Toast Notifications for Whole App.
https://github.com/user-attachments/assets/47bb05cb-f008-40bb-a77f-b8cd094e0415
Completed #62
> Added Email Validation in Newsletter and Toast Alerts Addition for Whole App | Issue #62

- src/app/(pages)/Events/EventItem.js
- src/app/(pages)/SingleEvent/[id]/page.jsx
<hr/>
This is in response to the page #40
> event Details Page

- src/components/Global/Hero.jsx
- src/components/ui/notification.jsx
**Title: Add Custom Notification Component to Hero Page**
**Summary:**
This PR introduces a custom notification component to the project, #66 . The notification is implemented in the file located at `src/ui/notification.jsx` and can be imported into the Hero Page as needed. The custom notification component allows for dynamic alerts or messages to be displayed on the Hero Page, enhancing the user experience by providing real-time feedback or updates.
**Changes Implemented:**
- Created a custom notification component in `src/ui/notification.jsx`.
- The component provides a flexible interface for triggering notifications with various types (e.g., success, error, warning).
- Added state management to control visibility and types of notifications.
- Notifications are styled to align with the …
> Popup Notification on Hero Page

- src/app/globals.css
I made the scrollbar hidden, and now the progressbar represent the scrolling progress.
https://github.com/user-attachments/assets/6814cd34-d600-4bc0-83eb-6ee611706ed5
Completed #75
> Hide the scrollbar | Issue #75

- src/components/Global/Footer.jsx
**PR Title: Enhance Footer Design with Social Media Links and Legal Information (#72) updated the Footer Component.**
**Issue Reference: #72**
This PR implements several enhancements to the website footer, improving both its visual appeal and functionality. The following features have been added to address the needs outlined in Issue #72:
1. **Visually Appealing Design:**
- Redesigned the footer to provide a cleaner and more modern look.
- Organized content into sections to improve readability and user experience.
- Enhanced color scheme and spacing for better visual balance.
- Added GDSC-RCCIIT logo and name for attraction.
2. **Social Media Links:**
- Added links to all relevant social platforms:
- Instagram
- WhatsApp
- LinkedIn
- GitHub
- Each link is represented by an icon, which …
> Update Footer Component

- src/app/(pages)/SignIn/page.jsx
- src/app/(pages)/SignUp/page.jsx
I have added the following:-
1. Enhance the UI of the SignIn & the SignUp Form.
2. Added Validation in Both Forms (Email, Password Validation)
3. Implemented the SignIn & SignUp Logic by LocalStorage Usage.
**Before**
**Updated One With Comparision**
https://github.com/user-attachments/assets/322ef6ef-1611-4452-95d2-84583d314dc7
Completed #53
> Sign in sign up implementation | Form Styling Enhancements | Validation Addition | Issue #53

- src/app/(pages)/Projects/page.jsx
This is on response to the issue #92
> Framer motion added to Projects page

- src/app/(pages)/Resources/page.jsx
https://github.com/user-attachments/assets/f8bc5307-927a-4b8c-8802-4f80a3c4376c
This is in response to the issue #93
> Framer animation on Resources Page

- src/app/(pages)/About/page.jsx
https://github.com/user-attachments/assets/fc8c3e86-68af-4543-9c02-1f02c348fc11
This is in response to the issue #94
> added animation to about Page

- src/app/(pages)/Events/EventItem.js
- src/app/(pages)/Events/Events.css
- src/app/(pages)/Events/page.jsx
https://github.com/user-attachments/assets/4df0949a-1566-4c25-a7b6-cbdc5b7547fe
This is in response to the issue #97
> motion added to Events Page

- src/app/(pages)/Projects/Card.jsx
Fix #112 
Added consistency in container heights.
> Fix UI Consistancy | Issue #112

- .github/workflows/greetings.yml
Fixed #109 
- **Read and write permissions** are required for certain operations, such as posting comments on issues or modifying pull requests.
- To enable these permissions, go to **Repository Settings** → **Actions** → **General** → **Workflow permissions** and select **Read and write permissions** under Workflow permissions.
- Then the Greeting messages would appear on every issue and pullrequests.
**Note:** Make sure to add all the necessary labels in #109
@GDSC-RCCIIT
> Added greetings on issues and pr

- src/app/(pages)/Events/Events.css
- src/components/Global/Footer.jsx
- src/components/Global/Header.jsx
- src/components/ui/progress-bar.jsx
fix #85
- **Return to Home Page on Logo Click**
- **Add a Light Gradient Background to Events Page**
-  **Fix footer styling** 
- **Optimize Colors for Existing Progress Bar**
Hey @rishicds please review my PR.
> Multiple UI/UX Enhancements and Fixes 

- src/app/(pages)/Projects/page.jsx
> Add searach bar to the project page

- src/components/Global/Hero.jsx
- src/components/ui/homepage.jsx
This is in response to the issue #101 
https://github.com/user-attachments/assets/e151f5c2-1249-4fb0-880b-11438e98c201
> Landing Page animation

- src/app/(pages)/PrivacyPolicy/page.jsx
- src/components/Global/Footer.jsx
This is in response to issue #102
> Privacy Policy Page

- src/app/(pages)/TermsAndConditions/page.jsx
- src/components/Global/Footer.jsx
This is in response to the issue #143
Hey @rishicds I made this page by mistake Prior to the Rules and Regulations Page but as far as I have seen their is no other issue on the same topic. Please assign it and merge it I will make the Rules and Regulations Page also. I have also added animations to the heading to make it same as the other Pages.
> Terms and conditions Page

- src/app/(pages)/RulesAndRegulations/page.jsx
- src/components/Global/Footer.jsx
This is in response to the issue #103
> Rules and Regulations Page

- src/app/layout.js
- src/components/GTranslateLoader.js
closes #115 
https://github.com/user-attachments/assets/e34f96cb-80a0-4dbe-ae3f-d74b7e9d0f85
> added multilanguage support for global accessibility closes #115

- src/components/Global/Hero.jsx
#150
Hey @rishicds please review my PR
> Add skeleton loading

- src/app/layout.js
fix: #157 
The application is running smooth now, the bug was beacuse of the chatbot and multilanguage support
> Sovled buggy code due to which application was not running 

- src/app/(pages)/orginizer/page.jsx
fix: #153 
This PR introduces a fully functional Organizer page within the application, designed to streamline event management tasks. Users will have the ability to create, edit, and view events, along with features such as managing participants and accessing event analytics. This addition aims to improve user experience and efficiency for those overseeing events, providing a centralized platform for all organizing activities.
> Implement Comprehensive Organizer Page for Enhanced Event Management Features

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/careers/[id]/page.jsx
- src/app/(pages)/careers/opportunities.js
- src/app/(pages)/careers/page.jsx
fix #170 
I have implemented a single page for the extended content of the opportunity on the careers page, that supports the Dynamic Routing of a Route.
E.g. Careers/[id]
It will extend the resources.
I also followed the modular approach that supports future enhancements in the careers opportunity easily( that I also used on all my pages)
Enhance the Card's UI of the Careers Page
https://github.com/user-attachments/assets/675e038f-5e88-493a-8715-3797897da347
Completed #170
> Extended Career Opportunity Page | Dynamic Routing of Careers Opportunity | Issue #170

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/Hackathon/page.jsx
- src/app/(pages)/Projects/page.jsx
- src/app/(pages)/Resources/page.jsx
- src/app/(pages)/TeamsGallery/page.jsx
fix #171 
I have added the skeleton loading on Skeleton Loading in Projects, Hackathons, Teams and Gallery, and Resources page.
https://github.com/user-attachments/assets/5464908a-637f-45ae-b304-ec5dddc6a5ea
Completed #171
> Added Skeleton Loading in Projects, Hackathons, Teams and Gallery, and Resources page

- .gitignore
- src/app/(pages)/TeamsGallery/page.jsx
Now all images added further down will follow this layout 2 on side and one on right 
#198
> Gallery corrected

- data.json
- src/app/(pages)/Hackathon/[id]/page.jsx
- src/app/(pages)/Hackathon/page.jsx
#195 
https://github.com/user-attachments/assets/b92a8235-3596-44e0-a597-e707a8d7624a
I have mapped the details there are still somethings left It is going to take a lot of time and efforts please merge this and for mapping it further I have added a lot of details in the hackathons data.json Do check and let me know which one You need shown. I will make another issue for this to display only necessary details Please provide me specific list.
Check out data.json file and let me know I added as much info as Possible from my side.
> mapped hackathon details

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/TechToolkits/page.jsx
- src/app/(pages)/TechToolkits/techStacks.js
- src/components/Global/Header.jsx
fix #187 
I have solved the common problem faced by any of us even a single time in our BTech or CS Related Upskilling.
Visiting Multiple Websites to download toolkits for different roadmaps tech stack.
For Detail Visit #187 
That's why I want to added a page for Tech Toolkits HUB for all the Tech Stack that will contains the following.
1. Create downloadable toolkits with software, IDEs, templates, and learning materials.
2. Offer collections for design assets, open-source tools, and frequently used coding libraries.
3. With Responsive Design.
https://github.com/user-attachments/assets/88928ad9-0d99-4239-b7a2-c51a6c0ce494
> Tech ToolKits HUB Page added | Issue #187

- src/app/(pages)/devStudent/page.jsx
fix: #216 
This PR adds a "Developer Student Club" page aimed at fostering a community for student developers. The page provides information about club activities, events, learning resources, and networking opportunities tailored for students. This addition seeks to encourage student participation, collaboration, and skill-building in a supportive environment.
> Add Developer Student Club Page to Engage and Support Student Developers

- src/app/(pages)/timeline/page.jsx
fix: #219
This PR adds a "Timeline" page, presenting a chronological view of key events, milestones, and upcoming activities. The page is designed to give users a clear overview of important dates, deadlines, and event progress, enhancing visibility and helping users stay informed about the application's development and community initiatives.
> Add Timeline Page to Display Key Events and Milestones

- src/app/(pages)/sustainable/page.jsx
- src/app/(pages)/timeline/page.jsx
fix: #220
This PR introduces a page dedicated to the United Nations' 17 Sustainable Development Goals (SDGs), aimed at raising awareness and promoting action toward a more sustainable future. The page provides an overview of each goal, including descriptions, objectives, and links to resourc
es for further learning. This addition seeks to engage users in global sustainability efforts and highlight the application’s commitment to these initiatives.
>  PR Title: Add Page for the 17 United Nations Sustainable Development Goals (SDGs)

- package-lock.json
- package.json
- src/app/(pages)/AddHackathon/page.jsx
- src/components/Global/AddHackathonForm.jsx
https://github.com/user-attachments/assets/0a7a0a9c-0c89-43af-9634-b794d9698df4
@rishicds Have a look
> hackathon form page

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/RulesAndRegulations/page.jsx
fix #279 
1. This update enhances the "Rules and Regulations" page by implementing a fixed sidebar for easy navigation. The sidebar contains links to various sections, ensuring users can quickly access information. 
2. The main content area has been adjusted to prevent overlap with the sidebar, providing a cleaner and more organized layout. 
3. Additionally, sections are now smoothly animated for a better user experience. 
Overall, these changes improve usability and accessibility on the page, making it easier for participants to engage with the content.
https://github.com/user-attachments/assets/29582d29-4afc-46ca-9234-c9f9911b5a5a
> Redesigned Rules and Regulations Page | Attractive UI | Modern Styling | Issue #279

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/PrivacyPolicy/page.jsx
fix #280 
1. This update enhances the "Privacy Policies" page by implementing a fixed sidebar for easy navigation. The sidebar contains links to various sections, ensuring users can quickly access information. 
2. The main content area has been adjusted to prevent overlap with the sidebar, providing a cleaner and more organized layout. 
3. Additionally, sections are now smoothly animated for a better user experience. 
Overall, these changes improve usability and accessibility on the page, making it easier for participants to engage with the content.
https://github.com/user-attachments/assets/009e351b-fbcb-45dc-9e47-5b156ec731f7
> Redesigned Privacy Policies Page | Attractive UI | Modern Styling | Issue #280

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/TermsAndConditions/page.jsx
fix #281 
1. This update enhances the "Terms and Conditions" page by implementing a fixed sidebar for easy navigation. The sidebar contains links to various sections, ensuring users can quickly access information. 
2. The main content area has been adjusted to prevent overlap with the sidebar, providing a cleaner and more organized layout. 
3. Additionally, sections are now smoothly animated for a better user experience. 
Overall, these changes improve usability and accessibility on the page, making it easier for participants to engage with the content.
https://github.com/user-attachments/assets/a4945c7a-9902-4995-92a2-5eab4667d10c
> Redesigned Terms and Conditions Page | Attractive UI | Modern Styling | Issue #281

- .github/workflows/auto_lable_issue.yml
> Fixed: workflow bug

- src/components/Global/Footer.jsx
- src/components/Global/Hero.jsx
- src/components/ui/homepage.jsx
Ui: fix the home page responsiveness #299 
Closes : #299 
https://github.com/user-attachments/assets/954f8cd8-4181-4781-a8ce-a785d91987eb
https://github.com/user-attachments/assets/2649be62-c7b1-4c15-85e6-9c2d29b89697
>  Ui: fix the home page responsiveness #299 

- src/app/(pages)/TechToolkits/page.jsx
- src/app/(pages)/TechToolkits/techStacks.js
This is in response to the issue #286 
https://github.com/user-attachments/assets/57f74c85-ad28-4c49-b74d-fe2af093e9cb
> Tech Toolkits Page

- .github/ISSUE_TEMPLATE/documentation-update.yml
- .github/ISSUE_TEMPLATE/enhancement-request.yml
Adding Enhancement Request, Documentation Update template
Issue - #312
> Adding Enhancement Request, Documentation Update template

- .github/PULL_REQUEST_TEMPLATE.md
Add the PULL REQUEST TEMPLATE
Issue - #315
> Add the PULL REQUEST TEMPLATE

- PROJECT_STRUCTURE.md
- data.json
- repo_structure.txt
- src/app/(pages)/Events/EventItem.js
- src/app/(pages)/Events/page.jsx
*Enter the issue title here-* Adde Support to Events Page To Fetch Events From JSON Server
---
I have added the Support in Events Page tp fetch Events Data from JSON Server
https://github.com/user-attachments/assets/a2bb673d-ea9a-484d-8607-ddd3ff1a4d74
---
*Enter your name here-* Shariq
---
Shariq2003
---
GSSOC Ext
---
*Closes: #231 
---
**Select the type of …
> Adde Support to Events Page To Fetch Events From JSON Server | Issue #231

- README.md
*Enter the issue title here-*  Add Stargazers & Forkers profiles to README.md 
---
To make project more interactive by displaying profiles to people who are forking project repository & giving start to repo.
---
*Enter your name here-* Shivanjali Karande
---
*Enter your GitHub ID here-*  shivanjalikarande
---
GSSOC, Hacktoberfest
*Enter your participant role here-*  Contributor
---
*Closes: #223 *
---
Added sections for forkers and stargazers profiles in README.md file at end
---
---
**Describe how …
> Updated readme.md by adding stargazers & forkers profiles

- .github/ISSUE_TEMPLATE/bug.yml
**CREATE BUG REPORT TEMPLATE**  
---
The goal is to create a standardized bug report template to streamline bug documentation, making it easier for contributors to report issues consistently and for maintainers to troubleshoot effectively.
---
**Alolika Bhowmik**
---
**alo7lika**
---
**GSSOC Contributor**  
---
**Closes: #309** 
---
**I created a bug report template with fields for title, description, steps to reproduce, expected and actual results, screenshots, environment details, and any additional information. This ensures consistency in bug reports, helping maintainers diagnose issues faster.**
---
---
**I verified the bug report template by creating sample issues using the template and ensuring that each field is …
> CREATE BUG REPORT TEMPLATE

- src/app/(pages)/FAQsForum/page.jsx
- src/app/(pages)/GeminiAI/page.jsx
- src/app/(pages)/Stories-Achievements/page.jsx
- src/app/(pages)/TechToolkits/page.jsx
- src/app/(pages)/expertdev/page.jsx
- src/app/(pages)/localdev/page.jsx
- src/app/(pages)/orginizer/page.jsx
- src/app/(pages)/stories/page.jsx
- src/app/(pages)/womentechmakers/page.jsx
fix #261 
I have added the Framer Motion Animation on the 9 pages, as follows:-
1. ExpertDev.
2. FAQs Forum
3. Gemini AI Chat
4. LocalDev
5. Organizer
6. Stories
7. Achievements
8. Tech Toolkits
9. and WomenTechMakers Page
https://github.com/user-attachments/assets/2a0553ca-fa46-4aa1-a943-be2f6d0d333a
> Added Framer Motion Animations on 9 Pages | Issue #261

- data.json
- src/app/(pages)/AddSpotlight/page.jsx
- src/app/(pages)/careers/page.jsx
- src/components/Global/AddSpotlightForm.jsx
fix #296 
I have added the following:-
1. Support of JSON Server in the Careers Page to Fetch Spotlights from JSON Server.
2. Added Spotlights Addition Feature along with the Form.
https://github.com/user-attachments/assets/b8903ffe-efdd-4501-9ac6-2eaa2c52a469
> Added Support for Spotlights from JSON Server in Careers Page along with the Add Opportunity Page | Issue #296

- .github/ISSUE_TEMPLATE/Custom.yml
*Enter the issue title here-*CREATE CUSTOM TEMPLATE
---
*Describe the aim of the project-*  
The goal of this project is to create a user-friendly platform that allows contributors to easily report issues and suggestions, enhancing collaboration and communication within the community.
---
*Enter your name here-*  
Alolika Bhowmik
---
*Enter your GitHub ID here-*  
alo7lika
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hacktoberfest).**  
*Enter your participant role here-*  
GSSOC Extended 2024
---
*Closes: #336*
---
**Give a clear description of what you have added or modified.** …
> CREATE CUSTOM TEMPLATE

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/Resources/[id]/page.jsx
- src/app/(pages)/Resources/resources.js
Addition of Backend Development Roadmap
---
Implementing a new roadmap, Backend Development Roadmap
---
V Pratheek
---
pratheekv39
---
Contributor at GSSOC and Hacktoberfest 
---
#366
--- …
> #366 Added the Backend Development Roadmap

- README.md
Add "Back to Top" in readme
---
I have created a back to top scroll up button in readme. This enhances easier navigation in length readme file for better user experience.
---
*Enter your name here-* Tatheer Fathima
---
*Enter your GitHub ID here-* T-Fathima
---
*Enter your participant role here-* Contributor in gssoc-ext 
---
*Closes: #318 *
---
**Describe how your changes have been tested.**  
*Describe your testing process here.*
Checked it's functionality …
> Add "Back to Top" in readme

- src/components/Global/Hero.jsx
contact us button is not working on home page
---
contact us button on home page is now working 
---
https://github.com/user-attachments/assets/3f60beb5-eea9-499a-8d4a-f5ef9b73000d
*Closes: #360 
---
---
- [X ] Bug fix (non-breaking change which fixes an issue)
---
**Describe how your changes have been tested.**  
*Describe your testing process here.*
- [ X] I have described my testing process.
---
> fix contact us button

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/Resources/resources.js
Addition of UI/UX Development Roadmap
---
Implementing UI/UX Roadmap 
---
V Pratheek
---
pratheekv39
---
---
#375
---
Modified the existing …
> #375 Implemented UI/UX Development Roadmap

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/Resources/resources.js
Addition of Cloud Computing & DevOps Roadmap
---
Addition of a new roadmap,  Cloud Computing & DevOps Roadmap
---
V Pratheek
---
pratheekv39
---
---
#383
---
*Describe your …
> #383 Added Cloud Computing and DevOps Roadmap

- src/app/(pages)/Stories-Achievements/[id]/page.jsx
- src/app/(pages)/Stories-Achievements/page.jsx
Make a new Page to display Stories and achievements like a blog #355
---
#355 
---
inkerton
---
inkerton
---
GSSOC
---
*Closes: #issue-number* #355
> Story details added

- src/app/(pages)/transform/page.jsx
> ADD Page for Transform with google cloude integration 

- src/app/(pages)/AddSpotlight/page.jsx
- src/components/Global/AddSpotlightForm.jsx
Added all fields in the Add career spotlight job according to json
---
inkerton
---
inkerton
---
GSSOC
---
*Closes: #issue-number* #292
---
```bash 
{
"id": "1",
"title": "Senior Staff Software Developer, Kubernetes",
"description": "Work on building the future of Kubernetes with our cloud-native team.",
"location": "Remote eligible",
"office": "Kirkland, WA, USA; +5 more",
"image": "/spot1.jpg",
"details": "As a Senior Software …
```
> Added all fields in the Add career spotlight job according to json

- src/app/(pages)/HelpWithFuture/page.jsx
- src/app/api/generate-content/route.js
- src/components/Global/HelpWithFutureForm.jsx
Add careers Page | Add student resources | Any other suggestions
I have added these questions 
---
inkerton
---
inkerton
---
GSSOC
---
*Closes: #issue-number* #292 
---
---
> Made a help with future questionaire Page

- src/app/(pages)/About/page.jsx
Hi @rishicds 
*Redesign of the About Page for Improved Responsiveness and Aesthetic Appeal*
---
*The goal of the project is to enhance the user experience of the About page by implementing a responsive design that is visually appealing and informative. This will help in providing better accessibility and engagement for users across different devices.*
---
*Devansh Vishwa*
---
*dev129*
---
*GSSOC*
---
*Fixes: #392 *
---
*I have redesigned the About page to improve its responsiveness on various screen sizes. This includes reworking the layout, updating the design for better styling, and ensuring that all elements are visually coherent and user-friendly. Additionally, I've optimized images and adjusted text sizes for better readability.*
---
**Select the …
> Update About Page

- src/app/(pages)/Resources/resources.js
*Enter the issue title here-* Open Source resource track added
- [X ] I have provided the issue title.
---
**What's the goal of the project?**  To give students an path to how to contribute in an open source project
*Describe the aim of the project-*  To give students an path to how to contribute in an open source project
- [X ] I have described the aim of the project.
---
*Enter your name here-* Vinay Anand Lodhi
- [X ] I have provided my name.
---
*Enter your GitHub ID here-* VinayLodhi1712
- [X ] I have provided my GitHub ID.
---
*Enter your participant …
> open source resources are added : #402 done

- src/app/(pages)/ai-ml/page.jsx
- src/app/(pages)/application-dev/page.jsx
> ADD Ai-Ml and Appllication development page

- src/app/(pages)/compute-tech/page.jsx
- src/app/(pages)/hosting/page.jsx
> Add 2PAGES compute tech and hositng page to the application 

- src/app/(pages)/analytics-pipelines/page.jsx
- src/app/(pages)/db-overview/page.jsx
>  Add  2Pages db overview and analytics page

- src/app/(pages)/distributed-hybrid/page.jsx
> Add Distributed, hybrid, and multicloud overview

- src/app/(pages)/generative-ai-overview/page.jsx
> Add Generative AI Overview page to the application 

- src/app/(pages)/industry-solutions/page.jsx
> Add Industry Solutions Overview page to the application

- src/app/(pages)/observability-view/page.jsx
> Add Observability and monitoring overview

- src/app/(pages)/security-overview/page.jsx
> Add security and overview implemenation for the applicationn

- src/app/(pages)/storage-overview/page.jsx
> Add storage and overview to the implementation 

- .github/ISSUE_TEMPLATE/frontend_issue.yml
*Enter the issue title here-* Front End Issue Report Template
---
*Describe the aim of the project-* To enhance the front end of the project by providing a structured issue reporting template, which helps streamline issue reporting and tracking.
---
*Enter your name here-* Alolika Bhowmik
---
*Enter your GitHub ID here-* alo7lika
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hacktoberfest).**  
*Enter your participant role here-* Contributor GSSOC 2024
---
*Closes: #issue-number* Closes: #401
---
**Give a clear …
> Front end Issue Report Template

- src/app/(pages)/get-started/page.jsx
> ADd get started page to the application 

- src/app/(pages)/join-partner/page.jsx
> Add join partner page for connecting people to the comunity

- src/app/(pages)/analyst-reports/page.jsx
> Add analyst report page to the application for thorough review fo reports data

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/Blogs/Blogs.js
- src/app/(pages)/Blogs/page.jsx
fix #427 
Implemented the Blogs Page | Search and SortBy Lexicographically Order(Increasing and Decreasing) | Fully Responsive
1. Blogs Listing.
2. Search Feature.
3. SortBy Feature.
https://github.com/user-attachments/assets/188ecbf9-a8bb-40f0-9c44-711bf3df3321
---
*Closes: #427 
---
---
> Implemented the Blogs Page | Search and SortBy Lexicographically Order(Increasing and Decreasing) | Fully Responsive | Issue #427

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/Resources/resources.js
Addition of Java Learning Roadmap
---
Added a new roadmap , Java Learning Roadmap
---
V Pratheek
---
pratheekv39
---
---
#379
---
Modified the …
> #379 Added Java Learning Roadmap

- .github/workflows/detect-duplicate.yml
- PROJECT_STRUCTURE.md
- repo_structure.txt
Add GitHub Workflow for Auto-Closing Similar Issue Requests
---
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, Hactoberfest).**  
*Enter your participant role here-* Contributor
---
*Closes: #420 *
---
> Add GitHub Workflow for Auto-Closing Similar Issue Requests

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/Blogs/Blogs.js
- src/app/(pages)/Blogs/[id]/page.jsx
- src/app/(pages)/Blogs/page.jsx
fix #427 
Implemented the Extended Blogs Page | Fully Responsive
1. Extended Blogs Page.
2. Dynamic Routing Addition of Blogs
3. Responsive UI.
https://github.com/user-attachments/assets/e9a5c5a4-af6d-484e-90eb-d6eb2d290f12
---
*Closes: #427 
---
---
> Implemented the Extended Blogs Page | Fully Responsive | Issue #427

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/HelpDesk/page.jsx
fix #426 
Added Help Desk Page.
---
*Closes: #426 
---
---
> Added Help Desk Page | Issue #426

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/Resources/resources.js
Addition of Machine Learning & AI Roadmap
---
Addition of a new roadmap, Machine Learning & AI Roadmap
---
V Pratheek
---
pratheekv39
---
---
#423
---
*Describe your changes …
> #423 Added Machine Learning & AI Roadmap 

- src/app/(pages)/Resources/resources.js
Addition of Blockchain Development Roadmap
---
Added the new roadmap,  Blockchain Development Roadmap
---
V Pratheek
---
pratheekv39
---
---
#452
---
*Describe your changes …
> #452 Added the Blockchain Development Roadmap

- src/app/(pages)/Resources/[id]/page.jsx
*Enter the issue title here-* resources overlapped in responsive mode corrected
- [X ] I have provided the issue title.
---
*Describe the aim of the project-* resources overlap in responsive mode ui fixed
- [ X] I have described the aim of the project.
---
*Enter your name here-* Vinay Anand Lodhi
- [ X] I have provided my name.
---
*Enter your GitHub ID here-* VinayLodhi1712
- [ X] I have provided my GitHub ID.
---
*Enter your participant role here-* GSSOC Hactoberfest
- [X ] I have mentioned my participant role.
--- …
> resources overlapped in responsive mode corrected

- src/app/globals.css
- src/app/layout.js
- src/components/Global/Navbar.jsx
- src/components/Global/Sidebar.jsx
**
updated navbar links[7/nov/2024]**
- **Home**  
- `layout.js`, `page.js` in `src`
- **Weekly Updates**  
- `/weekly/page.jsx`
- **About**  
- `/About/page.jsx`
- **Team Members**  
- `TeamsGallery/Teams.js`, `TeamsGallery/page.jsx`
- **Mission & Vision**  
- `mission.webp`, `vision.webp`
- **Privacy Policy**  
- `/PrivacyPolicy/page.jsx`
- **Terms and Conditions**  
- `/TermsAndConditions/page.jsx`
- **All Events**  
- `/Events/page.jsx`
- **Hackathons**  
- `/Hackathon/page.jsx`
- **Spotlight**  
- `/AddSpotlight/page.jsx`
- **Certifications**  
- `/Certifications/page.jsx`
- **Single Event**  
- `/SingleEvent/[id]/page.jsx`
- **All Projects**  
- `/Projects/page.jsx`
- **Add Project**  
- `/AddProjects/page.jsx`
- **Project Details**  
- `/Projects/[id]/page.jsx`
- **Resources Page** …
> Add sidebar and updated all the links according to the current website structure 

- src/app/(pages)/service-health/page.jsx
> ADD Service and health page fro the google developers resources 

- src/app/(pages)/code-exchange/page.jsx
> Add code-exchange page for better collaboration and easy connectivity 

- src/app/(pages)/storytime/page.jsx
fix: #438 
https://github.com/user-attachments/assets/ae385f7e-c6ed-4ed9-9099-465d541f90fc
> Add api story line page to the application 

- src/app/(pages)/moonshots/page.jsx
fix: #438 
Project Moonshot Hub
A tribute to Google’s ambitious projects like Project Loon and Waymo. This could feature case studies, APIs, or open data related to “moonshot” initiatives, showing developers how these groundbreaking projects are built, along with tips on innovating in tech.
> Add moonshots page to the application 

- src/app/(pages)/sandbox/page.jsx
fix: #438 
https://www.loom.com/share/974f374b659242879de1c899531bb20f?sid=36bd483d-6d94-4fd5-92d8-be17a1408928
> Add the sandbox page to the application 

- src/app/(pages)/Resources/resources.js
Hi @rishicds 
*Game Development Design for GDSC RCCIIT*
---
*The goal is to design and develop the Game Development section for the GDSC RCCIIT community.*
---
*Devansh Vishwa*
---
*dev129*
---
*GSSOC-EXT*
---
*Closes: #449 *
---
*I have contributed to the design of the Game Development section for GDSC RCCIIT, enhancing the layout, style, and structure to improve the user experience.*
---
---
**Describe how your changes have been tested.**  
*I tested the design changes by viewing them in different screen sizes and ensuring responsiveness, as well as ensuring that the visual elements …
> Game Dev Roadmap

- src/app/layout.js
- src/components/Global/Sidebar.jsx
fix : #483 
**changes done**
- fix mobile responsiveness for landing page 
- adjusted sidebar to match the theme and look 
- changed sidebar links
> Fix responsiveness for the application 

- src/app/(pages)/easter-egg/page.jsx
fix: #438 
1. Easter Egg Repository
A page dedicated to Google’s hidden Easter eggs, where developers can explore, learn, and even suggest new ones. It could include the code or logic behind each Easter egg and explain the thought process, inspiring creativity and fun.
> Add easter egg page to the application 

- src/app/(pages)/lens-page/page.jsx
fix: #438
A demo space where developers can explore Google Lens’s recognition capabilities. They could test how Lens detects and interprets images and even submit images for analysis to see how it’s done.
> ADD Google lens page for educating students about the google lens thing

- src/app/(pages)/Resources/resources.js
Hi @rishicds 
Roadmap for Robotics  
---
The goal of this project is to create a comprehensive roadmap for robotics, outlining key learning areas, resources, and project ideas for beginners and advanced learners to navigate their journey in robotics.  
---
Devansh Vishwa  
---
dev129  
---
GSSOC-EXT  
---
Closes: #480  
---
I have created a detailed roadmap for robotics, including topics such as basic electronics, programming, sensor integration, AI in robotics, and hands-on projects. I’ve also included links to relevant resources and tutorials to help learners advance in their robotics journey.  
---
---
I have reviewed the roadmap and tested all the links and resources included in it. The roadmap was shared with peers for feedback, and all suggestions were incorporated.  
---
> Roadmap for Robotics

- src/components/Global/Footer.jsx
*Enter the issue title here-* FOLLOW AND CONTACTUS DETAILS ARE SAME
- [YES] I have provided the issue title.
*Enter your name here-* MEET SHAH
- [YES] I have provided my name.
*Enter your GitHub ID here-* Meetpidev 
- [YES ] I have provided my GitHub ID.
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hactoberfest).**  GSSOC, HACTOBERFEST
*Enter your participant role here-* CONTRIBUTER
- [YES] I have mentioned my participant role.
*Closes: #459 *
- [YES] I have provided the issue number.
*Describe your changes here-* ADDED LINKS IN FOOTER
- [YES] I have described my changes.
---
- This change requires a documentation update
*Describe your testing process here.* CHECKED IN LOCALHOST
- [YES] I have …
> ADDED LINKS IN FOOTER AS PER YOUR REQUIREMENTS..

- src/app/(pages)/Resources/resources.js
*Enter the issue title here-* GIT & GITHUB LEARNING TRACK
- [YES] I have provided the issue title.
**What's the goal of the project?**  TO LEARN GIT AND GITHUB
*Describe the aim of the project-*  TO TEACH GIT AND GITHUB TO BEGINNERS
- [YES] I have described the aim of the project.
*Enter your name here-* MEET SHAH
- [YES] I have provided my name.
*Enter your GitHub ID here-* Meetpidev
- [YES] I have provided my GitHub ID.
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hactoberfest).**   GSSOC, Hactoberfest
*Enter your participant role here-* CONTRIBUTER
- [YES] I have mentioned my participant role.
*Closes: #460 *
- [YES] I have provided the issue number.
*Describe your changes here-* ADDED NEW …
> ADDED GIT & GITHUB LEARNING TRACK

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/Resources/resources.js
Hi @rishicds 
Creating a Linux Learning Roadmap
---
The goal of this project is to create a comprehensive roadmap for learning Linux, including examples, topics, and resources for beginners to advanced users. The roadmap will provide a structured path for learning Linux commands, system administration, shell scripting, kernel management, and other essential Linux topics.
---
Devansh Vishwa
---
dev129
---
gssoc-ext
---
Closes: #481 
---
I have created a detailed roadmap for learning Linux, which includes the following sections:
- **Introduction to Linux**: Overview of Linux distributions, installation methods, and the open-source ecosystem.
- **Basic Linux Commands**: A list of fundamental commands to navigate the system, manage files, and understand system processes.
- **System …
> Roadmap for Linux

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/TechToolkits/page.jsx
Hi @rishicds 
**Redesign the Tech Toolkits Page**  
*Redesign the Tech Toolkits page to enhance UI/UX.*
---
The goal is to redesign the Tech Toolkits page to improve its user interface and user experience by using a more interactive layout and animations, making it more engaging for the users to explore different tech stacks and tools.
---
Devansh Vishwa
---
dev129
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hacktoberfest).**  
Contributor in GSSOC-EXT
---
Closes: #482
---
---
The changes were tested by reviewing the UI/UX on various screen sizes to …
> Tech Tool page redesign 

- src/app/(pages)/polls/page.jsx
> Live Polls & Surveys for the application better scopign GDGC #501

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/louge/page.jsx
> Add GDG Virtual Lounge Feature

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/alumini/page.jsx
FIX: #509 
This PR introduces the **Alumni Network** page, designed to reconnect past GDG participants and contributors. The page serves as a platform for alumni to share experiences, offer career or academic advice, and connect with current members. It aims to foster a supportive community for knowledge sharing and professional growth.
- **Alumni Stories**: Showcase inspiring stories and testimonials from GDG alumni.
- **Career Advice**: A dedicated section where alumni can share guidance and advice on career paths.
- **Networking Opportunities**: Features for alumni and current members to connect and interact.
- **Job Board**: A space where alumni can post job openings or opportunities for members.
- Created sections for alumni stories, career advice, and networking.
- Added job board …
>  Add GDG Alumni Network Page

- src/app/(pages)/inovation-hub/page.jsx
> Add GDG Innovation Hub Page #511

- src/components/Global/Hero.jsx
*Enter the issue title here-*CLICKABLE CARDS
- [YES ] I have provided the issue title.
*Enter your name here-* MEET SHAH
- [YES ] I have provided my name.
---
*Enter your GitHub ID here-* Meetpidev
- [YES ] I have provided my GitHub ID.
---
*Enter your participant role here-* GSSOC,Hactoberfest
- [YES ] I have mentioned my participant role.
*Closes: #458 
- [YES ] I have provided the issue number.
---
*Describe your changes here-* MADE CARDS CLIKABLES
- [YES ] I have described my changes.
---
This change requires a documentation update
*Describe your testing process here.* TESED IN LOCALHOST
- [YES ] I have described my testing …
> MAKE CARDS CLICKABLES

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/Resources/resources.js
Addition of Quantum Computing Roadmap
---
Addition of a new roadmap, Quantum Computing Roadmap
---
V Pratheek
---
pratheekv39
---
---
#472
--- …
> #472 Added Quantum Computing Roadmap

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/code-exchange/page.jsx
Solved Runtime Error in the Code-Exchange Page | Addition of Code Copy Button | Addition of More Code Snippets
---
1. Solved Runtime Error in the Code-Exchange Page.
2. Added Code Copy Button.
3. Added More Code Snippets.
https://github.com/user-attachments/assets/cced5223-7ccb-480f-867e-933e94f7ec5b
---
> Solved Runtime Error in the Code-Exchange Page | Addition of Code Copy Button | Addition of More Code Snippets | Issue #527

- PROJECT_STRUCTURE.md
- repo_structure.txt
- src/app/(pages)/TechToolkits/page.jsx
fix #529 
Added links in the TechToolkits Page
https://github.com/user-attachments/assets/3762ef42-2386-43d0-ba9b-923065db6d0b
---
> Added links in the TechToolkits Page | Issue #529

- src/app/(pages)/mystery/page.jsx
> Add unsolved mystery tech

- src/app/(pages)/retro/page.jsx
> Add retro corner page to the applciation 

- src/app/(pages)/dev-nightmare/page.jsx
> Add Developer Nightmares Page to the application 

- src/app/(pages)/Resources/resources.js
*Enter the issue title here-*PYTHON LEARNING TRACK
- [YES ] I have provided the issue title.
---
**What's the goal of the project?**  LEARN PYTHON
*Describe the aim of the project-* LEARN PYTHON
- [YES ] I have described the aim of the project.
---
*Enter your name here-*MEET SHAH
- [YES ] I have provided my name.
---
*Enter your GitHub ID here-* Meetpidev
- [ YES] I have provided my GitHub ID.
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hactoberfest).**  GSSOC, Hactoberfest
*Enter your participant role here-* CONTRIBUTER
- [YES ] I have mentioned my participant role.
---
*Closes: #521 r*
- [ YES] I have provided the …
> ADDED  PYTHON LEARNING TRACK
